import turtle
pen = turtle.Pen()
pen.speed(0)
lenght = 200
password = turtle.textinput("password","密码:")
if password == "happy":
    
    pen.forward(lenght)
    pen.left(90)
    pen.forward(lenght)
    pen.left(90)
    pen.forward(lenght)
    pen.left(90)
    pen.forward(lenght)
    pen.left(90)
    pen.penup()

    pen.goto(50, 120)
    pen.pendown()
    pen.circle(20)
    pen.penup()
    pen.goto(50, 140)
    pen.pendown()
    pen.dot(15, "black")

    pen.penup()
    pen.goto(150, 120)
    pen.pendown()
    pen.circle(20)
    pen.penup()
    pen.goto(150, 140)
    pen.pendown()
    pen.dot(15, "black")

    pen.up()
    pen.goto(80, 60)
    #pen.pensize(10)
    pen.down()
    #pen.forward(110)
    pen.right(90)
    pen.circle(15,180)
    pen.hideturtle()
elif password == "sad":
    pen.forward(lenght)
    pen.left(90)
    pen.forward(lenght)
    pen.left(90)
    pen.forward(lenght)
    pen.left(90)
    pen.forward(lenght)
    pen.left(90)
    pen.penup()

    pen.goto(50, 120)
    pen.pendown()
    pen.circle(20)
    pen.penup()
    pen.goto(50, 140)
    pen.pendown()
    pen.dot(15, "black")

    pen.penup()
    pen.goto(150, 120)
    pen.pendown()
    pen.circle(20)
    pen.penup()
    pen.goto(150, 140)
    pen.pendown()
    pen.dot(15, "black")

    pen.up()
    pen.goto(120, 60)
    #pen.pensize(10)
    pen.down()
    #pen.forward(110)
    pen.right(270)
    pen.circle(15,180)
    pen.hideturtle()
else:
    turtle.write("error-77")
turtle.done()
